# pytorch张量的基础操作

In [1]:
import torch

In [3]:
# pytorch直接创建一个一维的张量,值是从0到给定的数字
x = torch.arange(12)

In [5]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
# numel即number of element 张量中元素的个数
x.numel()

12

In [7]:
# 这个函数和python的range函数类似是左闭右开的，所以(1,2)是从1开始但不包含2
y = torch.arange(1,2)
y

tensor([1])

In [13]:
# 使用shape查看张量的形状
y.shape

torch.Size([1])

In [21]:
# 在不改变张量值和内容的情况下改变其形状
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
# 把张量转换为一维
x.reshape(-1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# 生成全0或全1的张量
full_one = torch.ones(2,1)
full_zero = torch.zeros(3,2)
print(full_one)
print(full_zero)

tensor([[1.],
        [1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [25]:
# 通过列表或者嵌套列表构建张量
from_list = torch.tensor([[2,1,3],[4,6,1]])
from_list

tensor([[2, 1, 3],
        [4, 6, 1]])

In [27]:
# 张量支持+,-,*,/,**等运算,运算时会逐元素计算
target = from_list + from_list
print(target)
target = from_list * from_list
print(target)
target = from_list ** from_list
print(target)

tensor([[ 4,  2,  6],
        [ 8, 12,  2]])
tensor([[ 4,  1,  9],
        [16, 36,  1]])
tensor([[    4,     1,    27],
        [  256, 46656,     1]])


In [9]:
# 当进行运算的两个张量形状不同时,pytorch会使用广播机制将两个张量对齐为同一形状
# 要使用广播机制,pytorch会从最右边的维度开始检查,每个维度必须满足三个条件之一
# 1.相等
# 2.其中一个为1
# 3.其中一个不存在（即维度较少，缺失的维度自动视为 1）
test1 = torch.tensor([[2,4,1]])
test2 = torch.tensor([[1],[2],[3]])
target = test1 + test2
target

tensor([[3, 5, 2],
        [4, 6, 3],
        [5, 7, 4]])

In [11]:
# 可以使用cat()函数拼接两个张量
test3 = torch.arange(9).reshape(3,3)
torch.cat((test3,target),dim=0),torch.cat((test3,target),dim=1)

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8],
         [3, 5, 2],
         [4, 6, 3],
         [5, 7, 4]]),
 tensor([[0, 1, 2, 3, 5, 2],
         [3, 4, 5, 4, 6, 3],
         [6, 7, 8, 5, 7, 4]]))

In [13]:
# 使用stack对向量进行堆叠,cat()与stack()的不同之处在于,stack会得到更多的维度
torch.stack((test3, target), dim = 0) #新增一个用于区分两个test3和target的维度

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[3, 5, 2],
         [4, 6, 3],
         [5, 7, 4]]])

In [43]:
# 使用cat()时要保证拼接的维度相同,当指定dim=0时就必须保证两个拼接的张量的一行有同样多的元素
torch.cat((test3,test1),dim=0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [2, 4, 1]])

In [45]:
# 对所有元素求和
target.sum()

tensor(39)

In [51]:
# 将torch张量和numpy数据类型转换
A = target.numpy()
B = torch.tensor(A)
print(type(A))
print(type(B))
# 将只有一个元素的张量和python的基本类型转换
C = torch.tensor(3.5)
C.item(),float(C)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


(3.5, 3.5)

In [16]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C = torch.randn(3, 5)

# 矩阵乘法使用 matmul（或 @ 运算符）
out1 = torch.matmul(A, B)    # 等价于 A @ B
out2 = A @ B                 # 最简洁的写法
print(out1)
print(out2)

tensor([[ 1.0908, -1.6520,  1.0386,  0.4544,  1.3754],
        [ 1.0258, -1.2307,  1.9791,  1.1031,  1.2791],
        [ 0.3471,  0.8351, -0.3178,  0.3261,  0.0754]])
tensor([[ 1.0908, -1.6520,  1.0386,  0.4544,  1.3754],
        [ 1.0258, -1.2307,  1.9791,  1.1031,  1.2791],
        [ 0.3471,  0.8351, -0.3178,  0.3261,  0.0754]])


# 自动求导

In [1]:
import torch

In [15]:
x = torch.tensor([[2.,3.,4.],[1.,2.,3.]],requires_grad = True) # x.requires_grad = True等价于在创建时后面加requires_grad = True,必须是浮点数或者复数才能使用rad
x.grad

In [17]:
y = x ** 2
y

tensor([[ 4.,  9., 16.],
        [ 1.,  4.,  9.]], grad_fn=<PowBackward0>)

In [23]:
y.sum().backward() # backward函数只能对标量使用
x.grad

tensor([[4., 6., 8.],
        [2., 4., 6.]])

In [59]:
a = torch.tensor([1.,2.,3.])
a.requires_grad = True
z = 2 * torch.dot(a, a) #dot函数只能对一维张量使用,输出两个张量相乘后求和
z.backward() # 只有使用了backward()后梯度才会更新
x.grad

tensor([[4., 6., 8.],
        [2., 4., 6.]])

In [61]:
a.grad == 4 * a

tensor([True, True, True])

In [63]:
# 在默认情况下,grad会累积梯度我们需要手动清零
y = a.sum().backward()
a.grad == (4 * a + torch.ones_like(a)) 

tensor([True, True, True])

In [69]:
a.grad.zero_() # 手动清零

tensor([0., 0., 0.])

In [71]:
# 使用detach()将计算移动到记录的计算图之外
y = a * a
u = y.detach() #移除y之前的计算
z = u * a
z.sum().backward()
a.grad == u

tensor([True, True, True])

# nn.Module
pytorch的Module子类创建的参数都会自动注册到.parameters()中\
使用标准层会自动包装参数,如果要注册参数需要使用nn.Parameter(tensor)\
通过register_buffer()注册的参数不会更新\
子类一般会重写__init__()函数和forward()函数,nn.Sequential()函数实际相当于流水线的forward()函数\
当使用.eavl()或者.train()切换模型状态时会递归地运用于所有地子模块\
当使用.to(device)或者.float()来改变参数位置或者类型时也会递归地改变

In [24]:
import torch
import torch.nn as nn
net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10)) #线性层第一个维度视作透明,只会在第二个维度计算
X = torch.rand(2, 20)
print(net(X))

tensor([[-0.1452, -0.1385,  0.0963, -0.0446,  0.1429, -0.0920, -0.0726, -0.1930,
          0.1286, -0.0017],
        [-0.1353, -0.1025,  0.0496, -0.1999,  0.2705, -0.1227, -0.0128, -0.2239,
          0.0369, -0.0766]], grad_fn=<AddmmBackward0>)


In [34]:
#只有使用nn.Sequential()这样的可访问下标的创建方式才能这样写,如果是按创建类的方式创建module想这样访问就需要重写__getitem__()
print(net[2].state_dict()) 
print(net[2].bias) #访问最后一层的偏置
print(net[2].bias.data)

OrderedDict([('weight', tensor([[ 0.0440,  0.0524, -0.0057,  ..., -0.0042, -0.0335, -0.0308],
        [ 0.0579, -0.0006, -0.0337,  ..., -0.0282, -0.0414, -0.0605],
        [-0.0410, -0.0026,  0.0359,  ..., -0.0378, -0.0296,  0.0618],
        ...,
        [ 0.0511, -0.0129,  0.0429,  ..., -0.0473,  0.0556, -0.0224],
        [-0.0182,  0.0565, -0.0446,  ..., -0.0331, -0.0231,  0.0097],
        [-0.0468, -0.0224, -0.0192,  ...,  0.0025,  0.0223,  0.0085]])), ('bias', tensor([ 0.0012, -0.0257, -0.0076,  0.0446, -0.0080, -0.0118,  0.0044, -0.0547,
         0.0241,  0.0267]))])
Parameter containing:
tensor([ 0.0012, -0.0257, -0.0076,  0.0446, -0.0080, -0.0118,  0.0044, -0.0547,
         0.0241,  0.0267], requires_grad=True)
tensor([ 0.0012, -0.0257, -0.0076,  0.0446, -0.0080, -0.0118,  0.0044, -0.0547,
         0.0241,  0.0267])


In [8]:
class MyModule1(nn.Module):
    def __init__(self):
        '''
        init函数用于初始化模块的参数和层
        '''
        super().__init__() #init()函数一定要继承父类地init()函数
        self.hidden = nn.Linear(20, 256) #标准层中地参数会自动注册
        self.activation = nn.ReLU()
        self.out = nn.Linear(256, 10)
        self.para = nn.Parameter(torch.rand(2, 256)) #手动注册一个参数
        self.register_buffer("mask",torch.ones(2, 256)) #注册一个不会变的参数一般掩码就是不需要更新的参数

    
    def forward(self, x):
        '''
        forward参数用于定义计算较为复杂的逻辑
        '''
        x = self.hidden(x)
        x = x * self.para
        x = self.activation(x)
        x = x ** self.mask
        x = self.out(x)
        return x

model = MyModule1()
x = torch.randn(2, 20)
print("=== 输入 ===")
print(x.shape)

print("\n=== 所有可学习参数 ===")
# .parameters()返回的是一个generator对象里面是地址,使用.named_parameters()函数返回generator对象里面包含的是str和tensor
for name, p in model.named_parameters():
    print(f"  {name:20s} | shape: {str(p.shape):18s} | requires_grad: {p.requires_grad}")

print("\n=== state_dict (含buffer) ===")
for k, v in model.state_dict().items():
    print(f"  {k:20s} | shape: {v.shape}")

=== 输入 ===
torch.Size([2, 20])

=== 所有可学习参数 ===
  para                 | shape: torch.Size([2, 256]) | requires_grad: True
  hidden.weight        | shape: torch.Size([256, 20]) | requires_grad: True
  hidden.bias          | shape: torch.Size([256])  | requires_grad: True
  out.weight           | shape: torch.Size([10, 256]) | requires_grad: True
  out.bias             | shape: torch.Size([10])   | requires_grad: True

=== state_dict (含buffer) ===
  para                 | shape: torch.Size([2, 256])
  mask                 | shape: torch.Size([2, 256])
  hidden.weight        | shape: torch.Size([256, 20])
  hidden.bias          | shape: torch.Size([256])
  out.weight           | shape: torch.Size([10, 256])
  out.bias             | shape: torch.Size([10])


In [40]:
class MySequential(nn.Module):
    def __init__(self, *args):
        "可以通过参数列表来创建"
        super().__init__()
        net = nn.Sequential()
        for i,block in enumerate(args):
            net.add_module(f"block{i}",block) #可以给添加进来的模块命名
        '''
        或者
        for block in args:
            self._modules[block] = block 但这个方法直接访问了_modules不推荐
        '''
        # self.blocks = nn.ModuleList(args) 快速自动注册,但没有命名
            
    def forward(self, x):
        for block in self._modules.values():
            x = block(x)
        return x

net = MySequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))
net(x)

tensor([[-0.5079,  0.1574,  2.0855,  0.7255,  1.9560,  0.1332,  0.5489,  0.8304,
          0.9246, -2.8715, -2.2341, -0.6097, -0.5169, -2.3486, -0.5773, -1.1182,
          1.6351, -0.0108, -0.1406,  0.1881],
        [ 0.2131,  0.9048, -0.8922, -1.1723, -0.3316,  0.3520, -1.1155, -0.7327,
          0.6727,  2.0065,  0.0926, -1.5645, -0.7462,  0.3016, -0.3533, -2.0871,
          0.6658, -0.5272, -0.1674, -0.9581]])

In [48]:
# 让不同的层共享参数
x = torch.randn(2,4)
shared = nn.Linear(8, 8)
net1 = nn.Sequential(nn.Linear(4,8),nn.ReLU(),shared,nn.Linear(8,8),shared,nn.ReLU(),nn.Linear(8,1))
net1(x)
print(net1[2].weight == net1[4].weight)
net1[2].weight.data[0,0] = 100
print(net1[2].weight == net1[4].weight)

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])
tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])


# Dataset and DataLoader

## Dataset类
用于自定义数据集和对数据进行一些数据预处理主要实现三个函数:\
__init__()负责存储元信息（文件路径列表、标签数组、transform 对象）\
__len__()计算数据集的大小即有多少条数据\
__getitem__()函数定义如何加载单条数据以及怎么利用transform进行变换\
## DataLoader
数据加载器,用于封装Dataset,一般有四个比较重要的参数\
batch_size 定义批次大小\
shuffle=True 打乱加载顺序,即不会按照索引顺序依次加载\
num_workers 进程数\
drop_last=True 当使用 BatchNorm 时，尾批 size=1 会导致方差为 0 而 NaN\
collate_fn 定义一个函数用于定制batch的输出,默认的collate_fn会将同一个batch里的数据和标签分别拼接成tuple \

In [38]:
import torch
import time
from torch.utils.data import Dataset,DataLoader
# 对比将数据加载放在init和getitem中的比较
class EagerDataset(Dataset):
    '''
    验证将数据加载放在init中的耗时
    '''
    def __init__(self, n):
        super().__init__()
        start = time.time()
        self.data = [torch.randn(128) for _ in range(n)]
        self.labels = [torch.tensor(i % 10) for i in range(n)]
        print(f"加载耗时{time.time() - start}s")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

class LazyDataset(Dataset):
    '''
    getitem()函数是懒加载,需要的内存小于直接在init中加载数据
    '''
    def __init__(self, n):
        super().__init__()
        self.n = n

    def __len__(self):
        return self.n

    def __getitem__(self, idx):
        start = time.time()
        data = torch.randn(128)
        label = torch.tensor(idx % 10)
        print(f"加载耗时{time.time() - start}s")
        return data,label

ds_eager = EagerDataset(5000)
eager_loader = DataLoader(ds_eager, batch_size = 64) #DataLoader的第一个参数都是数据集,其它的参数尽量按关键字传
_ = next(iter(eager_loader)) #触发第一次加载

print("-------------------分隔符----------------------")
ds_lazy = LazyDataset(5000)
lazy_loader =  DataLoader(ds_lazy, batch_size = 64)
_ = next(iter(lazy_loader)) # 必须加上iter才能把DataLoader变成可迭代的

加载耗时0.4426736831665039s
-------------------分隔符----------------------
加载耗时0.0s
加载耗时0.0s
加载耗时0.0010082721710205078s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0010328292846679688s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0003991127014160156s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.001069784164428711s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s
加载耗时0.0s


In [20]:
# 验证默认collate_fn()函数怎么处理元组、字典和嵌套结构
import torch
from torch.utils.data.dataloader import default_collate

#标准元组
batch_tuple = [(torch.randn(2,3), torch.tensor(i)) for i in range(4)]
print(f"collate 前:{batch_tuple}")
res = default_collate(batch_tuple) #default_collate()函数的底层是stack而非cat函数,使用stack在没有batch维度时会自动创建batch维
print(f"类型: {type(res)}, 长度: {len(res)}")
print(f"data shape: {res[0].shape}, label shape: {res[1].shape}")
print(f"collate 后:{res}")

collate 前:[(tensor([[ 0.8562,  0.4813, -1.5892],
        [-0.3656,  0.9306,  1.6070]]), tensor(0)), (tensor([[-0.2530,  0.5716,  0.2555],
        [ 0.2031,  0.5736,  0.8867]]), tensor(1)), (tensor([[ 0.6814, -0.1029, -0.0262],
        [ 1.4918,  0.5366, -1.2338]]), tensor(2)), (tensor([[ 0.2628, -1.0917,  0.7482],
        [-1.6335,  0.1996, -0.0921]]), tensor(3))]
类型: <class 'list'>, 长度: 2
data shape: torch.Size([4, 2, 3]), label shape: torch.Size([4])
collate 后:[tensor([[[ 0.8562,  0.4813, -1.5892],
         [-0.3656,  0.9306,  1.6070]],

        [[-0.2530,  0.5716,  0.2555],
         [ 0.2031,  0.5736,  0.8867]],

        [[ 0.6814, -0.1029, -0.0262],
         [ 1.4918,  0.5366, -1.2338]],

        [[ 0.2628, -1.0917,  0.7482],
         [-1.6335,  0.1996, -0.0921]]]), tensor([0, 1, 2, 3])]


In [24]:
batch_dict = [
    {"img" : torch.randn(2), "lbl" : torch.tensor(0), "meta" : "cat"},
    {"img" : torch.randn(2), "lbl" : torch.tensor(1), "meta" : "dog"},
]
res = default_collate(batch_dict)
print(f"keys: {res.keys()}")
print(f"img shape: {res['img'].shape}, meta type: {type(res['meta'])}, meta: {res['meta']}")

keys: dict_keys(['img', 'lbl', 'meta'])
img shape: torch.Size([2, 2]), meta type: <class 'list'>, meta: ['cat', 'dog']


In [28]:
# 使用collate时,每个batch的张量形状要相同
try:
    bad_batch = [(torch.randn(3,2),), (torch.randn(5,2),)]
    default_collate(bad_batch)
except RuntimeError as e:
    print(f"捕获预期错误: {str(e)[:60]}...")

捕获预期错误: stack expects each tensor to be equal size, but got [3, 2] a...


In [34]:
#自定义collate()函数解决变长的形状
class VarlenDataset(Dataset):
    def __init__(self):
        #定义四条变长的数据,长度为3,4,5,2
        self.sentences = [
            torch.tensor([1.,2.,3.]),
            torch.tensor([4.,5.,6.,7.]),
            torch.tensor([8.,9.,10.,11.,12.]),
            torch.tensor([13.,14.])
        ]
        self.labels = [0 ,1 ,2 ,3]

    def __len__(self):
        return len(self.sentences)

    def __getitem__(self, idx):
        return self.sentences[idx], self.labels[idx]

# 自定义collate
def pad_collate(batch):
    '''
    该方法将所有张量的形状对齐为最长的张量形状
    '''
    #batch是一个列表,没一个数据按照(数据,标签)形式排列的,取用不太方便,因为一般都是取用数据进行一些转换操作,会频繁地使用索引来访问
    #当我们将batch中的数据和标签分别堆叠起来能够快速的对数据进行整体的操作
    #zip(*batch)是将batch中的数据取出来再按位置重新分组为[(s1, s2, s3), (l1, l2, l3)]
    sentences, labels = zip(*batch) # 转置: list of tuples → tuple of lists
    #计算当前batch长度最大的张量
    max_len = max(s.size(0) for s in sentences)
    
    #创建跟一个batch大小相等的全0pad
    padded = torch.zeros(len(sentences), max_len, dtype = torch.float)
    lengths = []

    #遍历sentences并填充张量
    for i,s in enumerate(sentences):
        padded[i, : s.size(0)] = s #一维的张量size(0)就是指序列长度,二维张量才是有多少行
        lengths.append(s.size(0))

    return padded, labels, lengths

loader = DataLoader(VarlenDataset(), batch_size = 4, collate_fn = pad_collate)
padded, labels, lengths = next(iter(loader))
print(f"Padded shape: {padded.shape}")  # 预期 [4, 5]
print(f"Padded tensor:\n{padded}")      # 短序列右侧应为0
print(f"Original lengths: {lengths}")   # 预期 [3, 5, 2, 4]
print(f"Labels: {labels}")              # 预期 [0, 1, 0, 1]

Padded shape: torch.Size([4, 5])
Padded tensor:
tensor([[ 1.,  2.,  3.,  0.,  0.],
        [ 4.,  5.,  6.,  7.,  0.],
        [ 8.,  9., 10., 11., 12.],
        [13., 14.,  0.,  0.,  0.]])
Original lengths: [3, 4, 5, 2]
Labels: (0, 1, 2, 3)
